version: "3.9"

networks:
  laravel:
    name: laravel

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - php
      - mysql
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  mysql:
    image: mysql:8.0.27
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    user: '1000:1000'
    volumes:
#      - /var/www/html/vendor
      - ./src:/var/www/html
#    command: "composer install && php artisan migrate"
    networks:
      - laravel

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - mysql
    ports:
      - 8080:8080
    logging:
      driver: none
    networks:
      - laravel
